### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by erfg12** [erfg12/memory.dll#66]
Currently requires .NET framework. Can we make this work for .NET core or make a second version for .NET core?

**Comment by domints** [comment]
Actually if you just remove Windows dependency (WinForms for MessageBox and administrator permission checking code) it works properly in .NET Core (won't work for sure in *nix, because kernel dll's are not available there, but compiles and works in Windows .NET Core app 100% correctly. Did that in my personal app I'm writing right now (don't think will ever release it, but if will, sure will mention you as the author of memory code).

To be honest I think this library could use some major refactoring, it just didn't annoy me enough to create refactoring fork yet :P

**Comment by haianh97** [comment]
Application net core can't find module address.

**Comment by domints** [comment]
Would you like to elaborate on the topic? Like I mentioned, I’ve
successfully run this code with .NET Core console app.

W dniu wt., 28.04.2020 o 01:34 haianh97 <notifications@github.com>
napisał(a):

**Comment by domints** [comment]
@haianh97 If you try to explain your problem with more details I might try helping you resolving it.

**Comment by erfg12** [comment]
I believe this is fixed now. https://github.com/erfg12/memory.dll/commit/191ddc2cb521ccc875e1deea1d3d562b2a4ef410
